refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  requests:
    kind: rolling_file
    path: logs.txt
    append: true
    encoder:
      kind: pattern
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: delete
root:
  level: info
  appenders:
    - stdout
    - requests